name: 'Code Style and List QA'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Setup node v18
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install deps from package-lock.json
        run: npm ci

      - name: Check prettier formatting
        run: "npm run format:check"

      - name: Check eslint rules
        run: npm run lint
